plugins
  {
    id "java"
    id "org.teavm" version "0.13.0"
  }

repositories { mavenCentral() }

java
  {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
  }

teavm
  {
    all
      {
        mainClass = "com.omegachess.GameLogicModule"
        debugInformation = false
      }
    wasm
      {
        //  Classic wasm target
      }
  }

